local f={

}
local codebook={
	{ code="A", clear="A"},
	{ code="E", clear="E"},
	{ code="N", clear="N"},
	{ code="I", clear="I"},
	{ code="S", clear="S"},
	{ code="R", clear="R"},
	{ code="A", clear="A"},
	{ code="T", clear="T"},
	{ code="D", clear="D"},
	{ code="H", clear="H"},
	{ code="U", clear="U"},
	{ code="L", clear="L"},
	{ code="C", clear="C"},
	{ code="G", clear="G"},
	{ code="M", clear="M"},
	{ code="O", clear="O"},
	{ code="B", clear="B"},
	{ code="W", clear="W"},
	{ code="F", clear="F"},
	{ code="K", clear="K"},
	{ code="Z", clear="Z"},
	{ code="P", clear="P"},
	{ code="V", clear="V"},
	{ code="J", clear="J"},
	{ code="Y", clear="Y"},
	{ code="XX", clear="X"},
	{ code="QQ", clear="Q"},
	{ code="XA", clear="THE"},
	{ code="XB", clear="AND"},
	{ code="XC", clear="THAT"},
	{ code="XD", clear="HAVE"},
	{ code="XE", clear="FOR"},
	{ code="XF", clear="NOT"},
	{ code="XG", clear="WITH"},
	{ code="XH", clear="YOU"},
	{ code="XI", clear="THIS"},
	{ code="XJ", clear="BUT"},
	{ code="XK", clear="HIS"},
	{ code="XL", clear="FROM"},
	{ code="XM", clear="THEY"},
	{ code="XN", clear="THA"},
	{ code="XO", clear="ENT"},
	{ code="XP", clear="ING"},
	{ code="XQ", clear="ION"},
	{ code="XR", clear="NDE"},
	{ code="XS", clear="HAS"},
	{ code="XT", clear="NCE"},
	{ code="XU", clear="EDT"},
	{ code="XV", clear="TIS"},
	{ code="XW", clear="OFT"},
	{ code="XY", clear="STH"},
	{ code="XZ", clear="MEN"},
}
return codebook
